### ISSUE TITLE
MOD with samples of a length above 65536 don't play correctly

### ISSUE THREAD

**Issue by DevanWolf** [jfdelnero/HxCModPlayer#5]
Modules with > 65536 length samples do exist but have issues on the player. The samples just treats as "65536 - sampleLength = short value" therefore other samples can be messed up as well making offsets.

[Two example files here](http://github.com/jfdelnero/HxCModPlayer/files/3414049/MODwithSamplesOver65536Examples.zip). Other players like OpenMPT play fine. Compare it with OpenMPT (or XMPlay) and your player.

**Comment by jfdelnero** [comment]
Thanks for the report. This is now fixed !
